# Default values for grepptimedb-operator

greptimedbOperatorRBAC:
  create: true
  serviceAccountName: greptimedb-operator
  clusterRoleName: manager-role
  clusterRoleBindingName: manager-rolebinding
  roleName: leader-election-role
  roleBindingName: leader-election-rolebinding

greptimedbOperator:
  create: true
  name: greptimedb-operator
  image: localhost:5001/greptime/greptimedb-operator:latest
  labels: controller-manager
  imagePullPolicy: IfNotPresent
  serviceAccount: greptimedb-operator
  terminationGracePeriodSeconds: 10
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  livenessProbe:
    httpGet:
      path: /healthz
      port: 9494
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessProbe:
    httpGet:
      path: /readyz
      port: 9494
    initialDelaySeconds: 5
    periodSeconds: 10
  args:
    - --enable-leader-election
  command:
    - greptimedb-operator

greptimedbCluster:
  create: true
  name: mock
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 250m
      memory: 64Mi
  frontend:
    replicas: 1
    image: localhost:5001/greptime/frontend:latest
    args:
      - -meta-endpoint
      - http://mock-meta.default:3001
      - -l
      - 0.0.0.0:3306
      - -r
      - mock-datanode.default:3306
  meta:
    replicas: 1
    image: localhost:5001/greptime/meta:latest
    args:
      - --etcd-endpoint
      - mock-etcd.default:2379
  datanode:
    replicas: 1
    image: localhost:5001/greptime/greptimedb:latest
