// Copyright 2022 Greptime Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/GreptimeTeam/greptimedb-operator/apis/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GreptimeDBStandaloneLister helps list GreptimeDBStandalones.
// All objects returned here must be treated as read-only.
type GreptimeDBStandaloneLister interface {
	// List lists all GreptimeDBStandalones in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.GreptimeDBStandalone, err error)
	// GreptimeDBStandalones returns an object that can list and get GreptimeDBStandalones.
	GreptimeDBStandalones(namespace string) GreptimeDBStandaloneNamespaceLister
	GreptimeDBStandaloneListerExpansion
}

// greptimeDBStandaloneLister implements the GreptimeDBStandaloneLister interface.
type greptimeDBStandaloneLister struct {
	indexer cache.Indexer
}

// NewGreptimeDBStandaloneLister returns a new GreptimeDBStandaloneLister.
func NewGreptimeDBStandaloneLister(indexer cache.Indexer) GreptimeDBStandaloneLister {
	return &greptimeDBStandaloneLister{indexer: indexer}
}

// List lists all GreptimeDBStandalones in the indexer.
func (s *greptimeDBStandaloneLister) List(selector labels.Selector) (ret []*v1alpha1.GreptimeDBStandalone, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.GreptimeDBStandalone))
	})
	return ret, err
}

// GreptimeDBStandalones returns an object that can list and get GreptimeDBStandalones.
func (s *greptimeDBStandaloneLister) GreptimeDBStandalones(namespace string) GreptimeDBStandaloneNamespaceLister {
	return greptimeDBStandaloneNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// GreptimeDBStandaloneNamespaceLister helps list and get GreptimeDBStandalones.
// All objects returned here must be treated as read-only.
type GreptimeDBStandaloneNamespaceLister interface {
	// List lists all GreptimeDBStandalones in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.GreptimeDBStandalone, err error)
	// Get retrieves the GreptimeDBStandalone from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.GreptimeDBStandalone, error)
	GreptimeDBStandaloneNamespaceListerExpansion
}

// greptimeDBStandaloneNamespaceLister implements the GreptimeDBStandaloneNamespaceLister
// interface.
type greptimeDBStandaloneNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all GreptimeDBStandalones in the indexer for a given namespace.
func (s greptimeDBStandaloneNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.GreptimeDBStandalone, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.GreptimeDBStandalone))
	})
	return ret, err
}

// Get retrieves the GreptimeDBStandalone from the indexer for a given namespace and name.
func (s greptimeDBStandaloneNamespaceLister) Get(name string) (*v1alpha1.GreptimeDBStandalone, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("greptimedbstandalone"), name)
	}
	return obj.(*v1alpha1.GreptimeDBStandalone), nil
}
