// Copyright 2022 Greptime Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apisv1alpha1 "github.com/GreptimeTeam/greptimedb-operator/apis/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// GreptimeDBClusterLister helps list GreptimeDBClusters.
// All objects returned here must be treated as read-only.
type GreptimeDBClusterLister interface {
	// List lists all GreptimeDBClusters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apisv1alpha1.GreptimeDBCluster, err error)
	// GreptimeDBClusters returns an object that can list and get GreptimeDBClusters.
	GreptimeDBClusters(namespace string) GreptimeDBClusterNamespaceLister
	GreptimeDBClusterListerExpansion
}

// greptimeDBClusterLister implements the GreptimeDBClusterLister interface.
type greptimeDBClusterLister struct {
	listers.ResourceIndexer[*apisv1alpha1.GreptimeDBCluster]
}

// NewGreptimeDBClusterLister returns a new GreptimeDBClusterLister.
func NewGreptimeDBClusterLister(indexer cache.Indexer) GreptimeDBClusterLister {
	return &greptimeDBClusterLister{listers.New[*apisv1alpha1.GreptimeDBCluster](indexer, apisv1alpha1.Resource("greptimedbcluster"))}
}

// GreptimeDBClusters returns an object that can list and get GreptimeDBClusters.
func (s *greptimeDBClusterLister) GreptimeDBClusters(namespace string) GreptimeDBClusterNamespaceLister {
	return greptimeDBClusterNamespaceLister{listers.NewNamespaced[*apisv1alpha1.GreptimeDBCluster](s.ResourceIndexer, namespace)}
}

// GreptimeDBClusterNamespaceLister helps list and get GreptimeDBClusters.
// All objects returned here must be treated as read-only.
type GreptimeDBClusterNamespaceLister interface {
	// List lists all GreptimeDBClusters in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apisv1alpha1.GreptimeDBCluster, err error)
	// Get retrieves the GreptimeDBCluster from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apisv1alpha1.GreptimeDBCluster, error)
	GreptimeDBClusterNamespaceListerExpansion
}

// greptimeDBClusterNamespaceLister implements the GreptimeDBClusterNamespaceLister
// interface.
type greptimeDBClusterNamespaceLister struct {
	listers.ResourceIndexer[*apisv1alpha1.GreptimeDBCluster]
}
