// Copyright 2022 Greptime Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/GreptimeTeam/greptimedb-operator/apis/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GreptimeDBClusterLister helps list GreptimeDBClusters.
// All objects returned here must be treated as read-only.
type GreptimeDBClusterLister interface {
	// List lists all GreptimeDBClusters in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.GreptimeDBCluster, err error)
	// GreptimeDBClusters returns an object that can list and get GreptimeDBClusters.
	GreptimeDBClusters(namespace string) GreptimeDBClusterNamespaceLister
	GreptimeDBClusterListerExpansion
}

// greptimeDBClusterLister implements the GreptimeDBClusterLister interface.
type greptimeDBClusterLister struct {
	indexer cache.Indexer
}

// NewGreptimeDBClusterLister returns a new GreptimeDBClusterLister.
func NewGreptimeDBClusterLister(indexer cache.Indexer) GreptimeDBClusterLister {
	return &greptimeDBClusterLister{indexer: indexer}
}

// List lists all GreptimeDBClusters in the indexer.
func (s *greptimeDBClusterLister) List(selector labels.Selector) (ret []*v1alpha1.GreptimeDBCluster, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.GreptimeDBCluster))
	})
	return ret, err
}

// GreptimeDBClusters returns an object that can list and get GreptimeDBClusters.
func (s *greptimeDBClusterLister) GreptimeDBClusters(namespace string) GreptimeDBClusterNamespaceLister {
	return greptimeDBClusterNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// GreptimeDBClusterNamespaceLister helps list and get GreptimeDBClusters.
// All objects returned here must be treated as read-only.
type GreptimeDBClusterNamespaceLister interface {
	// List lists all GreptimeDBClusters in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.GreptimeDBCluster, err error)
	// Get retrieves the GreptimeDBCluster from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.GreptimeDBCluster, error)
	GreptimeDBClusterNamespaceListerExpansion
}

// greptimeDBClusterNamespaceLister implements the GreptimeDBClusterNamespaceLister
// interface.
type greptimeDBClusterNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all GreptimeDBClusters in the indexer for a given namespace.
func (s greptimeDBClusterNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.GreptimeDBCluster, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.GreptimeDBCluster))
	})
	return ret, err
}

// Get retrieves the GreptimeDBCluster from the indexer for a given namespace and name.
func (s greptimeDBClusterNamespaceLister) Get(name string) (*v1alpha1.GreptimeDBCluster, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("greptimedbcluster"), name)
	}
	return obj.(*v1alpha1.GreptimeDBCluster), nil
}
