// Copyright 2022 Greptime Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/GreptimeTeam/greptimedb-operator/apis/v1alpha1"
	scheme "github.com/GreptimeTeam/greptimedb-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GreptimeDBClustersGetter has a method to return a GreptimeDBClusterInterface.
// A group's client should implement this interface.
type GreptimeDBClustersGetter interface {
	GreptimeDBClusters(namespace string) GreptimeDBClusterInterface
}

// GreptimeDBClusterInterface has methods to work with GreptimeDBCluster resources.
type GreptimeDBClusterInterface interface {
	Create(ctx context.Context, greptimeDBCluster *v1alpha1.GreptimeDBCluster, opts v1.CreateOptions) (*v1alpha1.GreptimeDBCluster, error)
	Update(ctx context.Context, greptimeDBCluster *v1alpha1.GreptimeDBCluster, opts v1.UpdateOptions) (*v1alpha1.GreptimeDBCluster, error)
	UpdateStatus(ctx context.Context, greptimeDBCluster *v1alpha1.GreptimeDBCluster, opts v1.UpdateOptions) (*v1alpha1.GreptimeDBCluster, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.GreptimeDBCluster, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GreptimeDBClusterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GreptimeDBCluster, err error)
	GreptimeDBClusterExpansion
}

// greptimeDBClusters implements GreptimeDBClusterInterface
type greptimeDBClusters struct {
	client rest.Interface
	ns     string
}

// newGreptimeDBClusters returns a GreptimeDBClusters
func newGreptimeDBClusters(c *ApisV1alpha1Client, namespace string) *greptimeDBClusters {
	return &greptimeDBClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the greptimeDBCluster, and returns the corresponding greptimeDBCluster object, and an error if there is any.
func (c *greptimeDBClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GreptimeDBCluster, err error) {
	result = &v1alpha1.GreptimeDBCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("greptimedbclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GreptimeDBClusters that match those selectors.
func (c *greptimeDBClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GreptimeDBClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GreptimeDBClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("greptimedbclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested greptimeDBClusters.
func (c *greptimeDBClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("greptimedbclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a greptimeDBCluster and creates it.  Returns the server's representation of the greptimeDBCluster, and an error, if there is any.
func (c *greptimeDBClusters) Create(ctx context.Context, greptimeDBCluster *v1alpha1.GreptimeDBCluster, opts v1.CreateOptions) (result *v1alpha1.GreptimeDBCluster, err error) {
	result = &v1alpha1.GreptimeDBCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("greptimedbclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(greptimeDBCluster).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a greptimeDBCluster and updates it. Returns the server's representation of the greptimeDBCluster, and an error, if there is any.
func (c *greptimeDBClusters) Update(ctx context.Context, greptimeDBCluster *v1alpha1.GreptimeDBCluster, opts v1.UpdateOptions) (result *v1alpha1.GreptimeDBCluster, err error) {
	result = &v1alpha1.GreptimeDBCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("greptimedbclusters").
		Name(greptimeDBCluster.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(greptimeDBCluster).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *greptimeDBClusters) UpdateStatus(ctx context.Context, greptimeDBCluster *v1alpha1.GreptimeDBCluster, opts v1.UpdateOptions) (result *v1alpha1.GreptimeDBCluster, err error) {
	result = &v1alpha1.GreptimeDBCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("greptimedbclusters").
		Name(greptimeDBCluster.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(greptimeDBCluster).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the greptimeDBCluster and deletes it. Returns an error if one occurs.
func (c *greptimeDBClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("greptimedbclusters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *greptimeDBClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("greptimedbclusters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched greptimeDBCluster.
func (c *greptimeDBClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GreptimeDBCluster, err error) {
	result = &v1alpha1.GreptimeDBCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("greptimedbclusters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
