apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  ports:
    - port: 2379
      name: client
    - port: 2380
      name: peer
  clusterIP: None
  selector:
    app: etcd
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-cluster
  labels:
    app: etcd
spec:
  selector:
    app: etcd
  ports:
    - port: 2379
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  serviceName: "etcd"
  replicas: 3
  selector:
    matchLabels:
      app: etcd
  volumeClaimTemplates:
    - metadata:
        name: etcd-storage
      spec:
        storageClassName: standard
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: bitnami/etcd:3.4.20
          command:
            - "etcd"
            - "--name"
            - "$(HOSTNAME)"
            - "--data-dir"
            - "/var/lib/etcd"
            - "--initial-advertise-peer-urls"
            - "http://$(HOSTNAME):2380"
            - "--listen-peer-urls"
            - "http://0.0.0.0:2380"
            - "--advertise-client-urls"
            - "http://$(HOSTNAME):2379"
            - "--listen-client-urls"
            - "http://0.0.0.0:2379"
            - "--initial-cluster"
            - "etcd-0=http://etcd-0.etcd:2380,etcd-1=http://etcd-1.etcd:2380,etcd-2=http://etcd-2.etcd:2380"
            - "--initial-cluster-state"
            - "new"
            - "--initial-cluster-token"
            - "etcd-cluster"
          volumeMounts:
          - name: etcd-storage
            mountPath: /var/lib/etcd
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ETCDCTL_API
              value: "3"
