# Copyright 2022 Greptime Team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  ports:
    - port: 2379
      name: client
    - port: 2380
      name: peer
  clusterIP: None
  selector:
    app: etcd
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-cluster
  labels:
    app: etcd
spec:
  selector:
    app: etcd
  ports:
    - port: 2379
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  labels:
    app: etcd
spec:
  serviceName: "etcd"
  replicas: 3
  selector:
    matchLabels:
      app: etcd
  volumeClaimTemplates:
    - metadata:
        name: etcd-storage
      spec:
        storageClassName: standard
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: greptime/etcd:v3.5.5
          command:
            - "etcd"
            - "--name"
            - "$(HOSTNAME)"
            - "--data-dir"
            - "/var/lib/etcd"
            - "--initial-advertise-peer-urls"
            - "http://$(HOSTNAME):2380"
            - "--listen-peer-urls"
            - "http://0.0.0.0:2380"
            - "--advertise-client-urls"
            - "http://$(HOSTNAME):2379"
            - "--listen-client-urls"
            - "http://0.0.0.0:2379"
            - "--initial-cluster"
            - "etcd-0=http://etcd-0.etcd:2380,etcd-1=http://etcd-1.etcd:2380,etcd-2=http://etcd-2.etcd:2380"
            - "--initial-cluster-state"
            - "new"
            - "--initial-cluster-token"
            - "etcd-cluster"
          volumeMounts:
          - name: etcd-storage
            mountPath: /var/lib/etcd
          ports:
            - containerPort: 2379
              name: client
            - containerPort: 2380
              name: peer
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ETCDCTL_API
              value: "3"
