apiVersion: greptime.io/v1alpha1
kind: GreptimeDBCluster
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  base:
    {{- if .Values.base.main.image }}
    image: {{ .Values.base.main.image }}
    {{- end }}
    main:
      resources:
        requests:
          memory: {{ .Values.base.main.resources.requests.memory }}
          cpu: {{ .Values.base.main.resources.requests.cpu }}
        limits:
          memory:  {{ .Values.base.main.resources.limits.memory }}
          cpu: {{ .Values.base.main.resources.limits.cpu }}
  frontend:
    replicas: {{ .Values.frontend.replicas }}
    template:
      main:
        {{- if .Values.frontend.main.image }}
        image: {{ .Values.frontend.main.image }}
        {{- end }}
        args:
          - "-meta-endpoint"
          - "http://{{ .Release.Name }}-meta.{{ .Release.Namespace }}:3001"
          - "-l"
          - "0.0.0.0:3306"
          - "-r"
          - "{{ .Release.Name }}-datanode.{{ .Release.Namespace }}:3306"
  meta:
    replicas: {{ .Values.meta.replicas }}
    etcdEndpoints:
      - "{{ .Release.Name }}-etcd-svc.{{ .Release.Namespace }}:{{ .Values.etcd.servicePorts.client }}"
    template:
      main:
        {{- if .Values.meta.main.image }}
        image: {{ .Values.meta.main.image }}
        {{- end }}
        args:
          - "--etcd-endpoint"
          - "{{ .Release.Name }}-etcd-svc.{{ .Release.Namespace }}:{{ .Values.etcd.servicePorts.client }}"
  datanode:
    replicas: {{ .Values.datanode.replicas }}
    template:
      main:
        {{- if .Values.datanode.main.image }}
        image: {{ .Values.datanode.main.image }}
        {{- end }}
    storage:
      storageClassName: {{ .Values.datanode.storage.storageClassName }}
      storageSize: {{ .Values.datanode.storage.storageSize }}
      storageRetainPolicy: {{ .Values.datanode.storage.storageRetainPolicy }}
  enablePrometheusMonitor: false
