apiVersion: greptime.io/v1alpha1
kind: GreptimeDBCluster
metadata:
  name: cluster-with-monitor
spec:
  base:
    main:
      image: greptime/greptimedb:latest
  frontend:
    replicas: 1
  meta:
    replicas: 1
    backendStorage:
      etcd:
        endpoints:
          - "etcd.etcd-cluster.svc.cluster.local:2379"
  datanode:
    replicas: 1
  prometheusMonitor: # Make sure you have already installed prometheus-operator and created a Prometheus instance with the label `release=prometheus`.
    enabled: true
    interval: "30s"
    labels:
      release: prometheus
