{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "greptimedb-operator.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "greptimedb-operator.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "greptimedb-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
