apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "greptimedb-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "greptimedb-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "greptimedb-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        {{- include "greptimedb-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "greptimedb-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      containers:
      - name: manager
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9494
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9494
          initialDelaySeconds: 5
          periodSeconds: 10
        args:
          - --enable-leader-election
        command:
          - greptimedb-operator
        resources:
{{ toYaml .Values.resources | indent 12 }}
