{{- if .Values.greptimedbCluster.create }}
apiVersion: greptime.cloud/v1alpha1
kind: GreptimeDBCluster
metadata:
  name: {{ .Values.greptimedbCluster.name }}
  namespace: {{ .Release.Namespace }}
spec:
  base:
    main:
      resources:
{{ toYaml .Values.greptimedbCluster.resources | indent 12 }}
    {{- end}}
  frontend:
    replicas: {{ .Values.greptimedbCluster.frontend.replicas }}
    template:
      main:
        image: {{ .Values.greptimedbCluster.frontend.image }}
        args:
          {{- range $.Values.greptimedbCluster.frontend.args }}
          - {{ . | quote }}
          {{- end }}
  meta:
    replicas: {{ .Values.greptimedbCluster.meta.replicas }}
    template:
      main:
        image: {{ .Values.greptimedbCluster.meta.image }}
        args:
          {{- range $.Values.greptimedbCluster.meta.args }}
          - {{ . | quote }}
          {{- end }}
  datanode:
    replicas: {{ .Values.greptimedbCluster.datanode.replicas }}
    template:
      main:
        image: {{ .Values.greptimedbCluster.datanode.image }}
