apiVersion: greptime.io/v1alpha1
kind: GreptimeDBCluster
metadata:
  name: cluster-with-dedicated-wal
spec:
  base:
    main:
      image: greptime/greptimedb:latest
  frontend:
    replicas: 1
  meta:
    replicas: 1
    backendStorage:
      etcd:
        endpoints:
          - "etcd.etcd-cluster.svc.cluster.local:2379"
  datanode:
    replicas: 1
  wal:
    raftEngine:
      fs:
        storageClassName: io2 # Use io2 storage class for WAL for better performance.
        name: wal
        storageSize: 5Gi
        mountPath: /wal
