---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - greptime.cloud
  resources:
  - greptimedbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - greptime.cloud
  resources:
  - greptimedbclusters/finalizers
  verbs:
  - update
- apiGroups:
  - greptime.cloud
  resources:
  - greptimedbclusters/status
  verbs:
  - get
  - patch
  - update
