apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: greptimedb-operator-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: greptimedb-operator
  namespace: greptimedb-operator-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: greptimedb-operator-leader-election-role
  namespace: greptimedb-operator-test
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: greptimedb-operator-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - greptime.io
  resources:
  - greptimedbclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - greptime.io
  resources:
  - greptimedbclusters/finalizers
  verbs:
  - update
- apiGroups:
  - greptime.io
  resources:
  - greptimedbclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - greptime.io
  resources:
  - greptimedbstandalones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - greptime.io
  resources:
  - greptimedbstandalones/finalizers
  verbs:
  - update
- apiGroups:
  - greptime.io
  resources:
  - greptimedbstandalones/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - podmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: greptimedb-operator-leader-election-rolebinding
  namespace: greptimedb-operator-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: greptimedb-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: greptimedb-operator
  namespace: greptimedb-operator-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: greptimedb-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: greptimedb-operator-role
subjects:
- kind: ServiceAccount
  name: greptimedb-operator
  namespace: greptimedb-operator-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: greptimedb-operator
  namespace: greptimedb-operator-test
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --enable-leader-election
        command:
        - greptimedb-operator
        image: localhost:5001/greptime/greptimedb-operator:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9494
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9494
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
      serviceAccountName: greptimedb-operator
      terminationGracePeriodSeconds: 10
