apiVersion: greptime.io/v1alpha1
kind: GreptimeDBCluster
metadata:
  name: cluster-with-tls
spec:
  base:
    main:
      image: greptime/greptimedb:latest
  frontend:
    replicas: 1
    tls:
      secretName: frontend-tls
  meta:
    replicas: 1
    etcdEndpoints:
      - "etcd.etcd-cluster.svc.cluster.local:2379"
  datanode:
    replicas: 1
