apiVersion: greptime.io/v1alpha1
kind: GreptimeDBCluster
metadata:
  name: cluster-with-kafka-remote-wal
spec:
  base:
    main:
      image: greptime/greptimedb:latest
  frontend:
    replicas: 1
  meta:
    replicas: 1
    etcdEndpoints:
      - "etcd.etcd-cluster.svc.cluster.local:2379"
    config: |
      [wal]
      provider = "kafka"
      broker_endpoints = ["kafka.kafka-cluster.svc.cluster.local:9092"]
  datanode:
    replicas: 1
    config: |
      [wal]
      provider = "kafka"
      broker_endpoints = ["kafka.kafka-cluster.svc.cluster.local:9092"]
      overwrite_entry_start_id = true
  wal:
    kafka:
      brokerEndpoints:
        - "kafka-bootstrap.kafka.svc.cluster.local:9092"
