apiVersion: greptime.io/v1alpha1
kind: GreptimeDBCluster
metadata:
  name: cluster-with-multiple-filestorage
spec:
  initializer:
    image: greptime-registry.cn-hangzhou.cr.aliyuncs.com/greptime/greptimedb-initializer:latest
  base:
    main:
      image: greptime-registry.cn-hangzhou.cr.aliyuncs.com/greptime/greptimedb:latest
  frontend:
    replicas: 1
  meta:
    replicas: 1
    etcdEndpoints:
      - "etcd.etcd-cluster:2379"
  datanode:
    replicas: 1
    storage:
      fs:
        storageClassName: standard
        name: index
        storageSize: 5Gi
        mountPath: /data/greptimedb/index_intermediate
        storageRetainPolicy: Retain
  wal:
    raftEngine:
      fs:
        storageClassName: standard
        name: wal
        storageSize: 5Gi
        mountPath: /data/greptimedb/wal
        storageRetainPolicy: Retain
