apiVersion: greptime.io/v1alpha1
kind: GreptimeDBCluster
metadata:
  name: configure-frontend-ingress
spec:
  initializer:
    image: greptime-registry.cn-hangzhou.cr.aliyuncs.com/greptime/greptimedb-initializer:latest
  base:
    main:
      image: greptime-registry.cn-hangzhou.cr.aliyuncs.com/greptime/greptimedb:latest
  frontend:
    replicas: 1
  meta:
    replicas: 1
    etcdEndpoints:
      - "etcd.etcd-cluster.svc.cluster.local:2379"
  datanode:
    replicas: 1
  ingress:
    annotations:
      dedicated: configure-frontend-ingress
    labels:
      dedicated: configure-frontend-ingress
    ingressClassName: nginx
    rules:
      - host: configure-frontend-ingress.example.com
        backends:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - configure-frontend-ingress.example.com
        secretName: configure-frontend-ingress-frontend-tls
