apiVersion: greptime.io/v1alpha1
kind: GreptimeDBCluster
metadata:
  name: basic
  namespace: default
spec:
  base:
    main:
      image: greptime/greptimedb:integration-paas-test
  frontend:
    replicas: 1
  meta:
    replicas: 1
    etcdEndpoints:
      - "etcd.default:2379"
  datanode:
    replicas: 3
