apiVersion: greptime.cloud/v1alpha1
kind: GreptimeDBCluster
metadata:
  name: basic-gt-cluster
  namespace: default
spec:
  base:
    main:
      image: greptime/greptimedb:latest
  frontend:
    replicas: 1
  meta:
    replicas: 3
  datanode:
    replicas: 1