apiVersion: greptime.cloud/v1alpha1
kind: GreptimeDBCluster
metadata:
  name: basic
  namespace: default
spec:
  base:
    main:
      image: localhost:5001/nginx:1.14.2
  frontend:
    replicas: 1
  meta:
    replicas: 3
  datanode:
    replicas: 1
