processors:
  - date:
      fields:
        - timestamp # 2024-08-30T08:55:48.817419Z
      formats:
        - "%Y-%m-%dT%H:%M:%S.%6fZ"

transform:
  - fields:
      - level
      - target
      - module_path
      - file
      - pod
      - pod_ip
      - namespace
      - cluster
      - role
      - cost
      - threshold
    type: string
    index: tag
  - fields:
      - message
      - query
      - err
    type: string
    index: fulltext
  - field: timestamp
    type: time
    index: timestamp
