processors:
  - date:
      fields:
        - timestamp # 2024-08-30T08:55:48.817419Z
      formats:
        - "%Y-%m-%dT%H:%M:%S.%6fZ"

transform:
  - fields:
      - pod_ip
      - namespace
      - cluster
      - cost
      - threshold
      - pod
    type: string

  - fields:
      - query
    type: string
    index: fulltext

  - field: timestamp
    type: time
    index: timestamp
