sources:
  logs:
    type: file
    data_dir: /logs
    include:
      - /logs/greptimedb-err.*
      - /logs/greptimedb.*
    max_read_bytes: 536870912

{{ if eq .EnableAuditLogs "true" }}
  audit_logs:
    type: file
    data_dir: /audit-logs
    include:
      - /audit-logs/*
    max_read_bytes: 536870912
{{ end }}

  metrics:
    type: prometheus_scrape
    endpoints:
      - "{{ .MetricsEndpoint }}"
    instance_tag: instance
    endpoint_tag: endpoint
    honor_labels: true

transforms:
  transform_logs:
    type: remap
    inputs:
      - logs
    source: |
      . = parse_json!(.message)
      .message = .fields.message
      .pod = "${POD_NAME}"
      .pod_ip = "${POD_IP}"
      .namespace = "${POD_NAMESPACE}"
      .cluster = "{{ .ClusterName }}"
      .role = "${ROLE}"
      if exists(.fields."log.target") {
        .target = .fields."log.target"
      }
      if exists(.fields."log.module_path") {
        .module_path = .fields."log.module_path"
      }
      if exists(.fields."log.file") {
        .file = .fields."log.file"
      }
      if exists(.fields."err") {
        .err = .fields.err
      }

{{ if eq .EnableAuditLogs "true" }}
  transform_audit_logs:
    type: remap
    inputs:
      - audit_logs
    source: |
      . = parse_json!(.message)
      .pod = "${POD_NAME}"
      .pod_ip = "${POD_IP}"
      .namespace = "${POD_NAMESPACE}"
      .cluster = "{{ .ClusterName }}"
      .role = "${ROLE}"
      if exists(.time) {
        .timestamp = .time
      }
      if exists(.object_names) && is_array(.object_names) {
        .object_names = join!(.object_names, ", ")
      }
{{ end }}

  add_metrics_labels:
    type: remap
    inputs:
      - metrics
    source: |
      .tags.namespace = "${POD_NAMESPACE}"
      .tags.cluster = "{{ .ClusterName }}"
      .tags.pod = "${POD_NAME}"

sinks:
  sink_greptimedb_logs:
    type: greptimedb_logs
    table: {{ .LogsTableName }}
    pipeline_name: {{ .LogsPipelineName }}
    compression: gzip
    inputs:
      - transform_logs
    endpoint: {{ .LoggingService }}
    extra_headers:
      x-greptime-hint-ttl: {{ .TTL }}

{{ if eq .EnableAuditLogs "true" }}
  sink_greptimedb_audit_logs:
    type: greptimedb_logs
    table: {{ .AuditLogsTableName }}
    pipeline_name: {{ .AuditLogsPipelineName }}
    compression: gzip
    inputs:
      - transform_audit_logs
    endpoint: {{ .LoggingService }}
    extra_headers:
      x-greptime-hint-ttl: {{ .TTL }}
{{ end }}

  sink_greptimedb_metrics:
    type: prometheus_remote_write
    inputs:
      - add_metrics_labels
    endpoint: {{ .MetricService }}
    request:
      headers:
        x-greptime-hint-ttl: {{ .TTL }}
