// Copyright 2022 Greptime Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/GreptimeTeam/greptimedb-operator/apis/v1alpha1"
	apisv1alpha1 "github.com/GreptimeTeam/greptimedb-operator/pkg/client/clientset/versioned/typed/apis/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeGreptimeDBClusters implements GreptimeDBClusterInterface
type fakeGreptimeDBClusters struct {
	*gentype.FakeClientWithList[*v1alpha1.GreptimeDBCluster, *v1alpha1.GreptimeDBClusterList]
	Fake *FakeApisV1alpha1
}

func newFakeGreptimeDBClusters(fake *FakeApisV1alpha1, namespace string) apisv1alpha1.GreptimeDBClusterInterface {
	return &fakeGreptimeDBClusters{
		gentype.NewFakeClientWithList[*v1alpha1.GreptimeDBCluster, *v1alpha1.GreptimeDBClusterList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("greptimedbclusters"),
			v1alpha1.SchemeGroupVersion.WithKind("GreptimeDBCluster"),
			func() *v1alpha1.GreptimeDBCluster { return &v1alpha1.GreptimeDBCluster{} },
			func() *v1alpha1.GreptimeDBClusterList { return &v1alpha1.GreptimeDBClusterList{} },
			func(dst, src *v1alpha1.GreptimeDBClusterList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.GreptimeDBClusterList) []*v1alpha1.GreptimeDBCluster {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.GreptimeDBClusterList, items []*v1alpha1.GreptimeDBCluster) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
