// Copyright 2022 Greptime Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/GreptimeTeam/greptimedb-operator/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGreptimeDBClusters implements GreptimeDBClusterInterface
type FakeGreptimeDBClusters struct {
	Fake *FakeApisV1alpha1
	ns   string
}

var greptimedbclustersResource = v1alpha1.SchemeGroupVersion.WithResource("greptimedbclusters")

var greptimedbclustersKind = v1alpha1.SchemeGroupVersion.WithKind("GreptimeDBCluster")

// Get takes name of the greptimeDBCluster, and returns the corresponding greptimeDBCluster object, and an error if there is any.
func (c *FakeGreptimeDBClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GreptimeDBCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(greptimedbclustersResource, c.ns, name), &v1alpha1.GreptimeDBCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GreptimeDBCluster), err
}

// List takes label and field selectors, and returns the list of GreptimeDBClusters that match those selectors.
func (c *FakeGreptimeDBClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GreptimeDBClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(greptimedbclustersResource, greptimedbclustersKind, c.ns, opts), &v1alpha1.GreptimeDBClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GreptimeDBClusterList{ListMeta: obj.(*v1alpha1.GreptimeDBClusterList).ListMeta}
	for _, item := range obj.(*v1alpha1.GreptimeDBClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested greptimeDBClusters.
func (c *FakeGreptimeDBClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(greptimedbclustersResource, c.ns, opts))

}

// Create takes the representation of a greptimeDBCluster and creates it.  Returns the server's representation of the greptimeDBCluster, and an error, if there is any.
func (c *FakeGreptimeDBClusters) Create(ctx context.Context, greptimeDBCluster *v1alpha1.GreptimeDBCluster, opts v1.CreateOptions) (result *v1alpha1.GreptimeDBCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(greptimedbclustersResource, c.ns, greptimeDBCluster), &v1alpha1.GreptimeDBCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GreptimeDBCluster), err
}

// Update takes the representation of a greptimeDBCluster and updates it. Returns the server's representation of the greptimeDBCluster, and an error, if there is any.
func (c *FakeGreptimeDBClusters) Update(ctx context.Context, greptimeDBCluster *v1alpha1.GreptimeDBCluster, opts v1.UpdateOptions) (result *v1alpha1.GreptimeDBCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(greptimedbclustersResource, c.ns, greptimeDBCluster), &v1alpha1.GreptimeDBCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GreptimeDBCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGreptimeDBClusters) UpdateStatus(ctx context.Context, greptimeDBCluster *v1alpha1.GreptimeDBCluster, opts v1.UpdateOptions) (*v1alpha1.GreptimeDBCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(greptimedbclustersResource, "status", c.ns, greptimeDBCluster), &v1alpha1.GreptimeDBCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GreptimeDBCluster), err
}

// Delete takes name of the greptimeDBCluster and deletes it. Returns an error if one occurs.
func (c *FakeGreptimeDBClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(greptimedbclustersResource, c.ns, name, opts), &v1alpha1.GreptimeDBCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGreptimeDBClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(greptimedbclustersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GreptimeDBClusterList{})
	return err
}

// Patch applies the patch and returns the patched greptimeDBCluster.
func (c *FakeGreptimeDBClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GreptimeDBCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(greptimedbclustersResource, c.ns, name, pt, data, subresources...), &v1alpha1.GreptimeDBCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GreptimeDBCluster), err
}
