name: Release
on: [push, pull_request]
#on:
#  push:
#    tags:
#      - '*'
#  pull_request:
#    tags:
#      - '*'

#env:
#  REGISTRY: ghcr.io
#  IMAGE_NAME: ${{ github.repository }}

jobs:
#  docker:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v4
#        with:
#          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v3
#        with:
#          file: ./Dockerfile
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

#      - name: Run chart-releaser
#        uses: helm/chart-releaser-action@v1.4.1
#        with:
#          charts_dir: ./charts/greptimedb-operator
#        env:
#          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Package Charts
        run: |
          helm package ./charts/greptimedb-operator
          helm package ./charts/greptimedb

      - name: Upload Release Asset
        uses: ncipollo/release-action@v1.11.1
        with:
          artifacts: |
            "greptimedb-0.1.0.tgz"
            "greptimedb-operator-0.1.0.tgz"
          token: "${{ secrets.GITHUB_TOKEN }}"
