name: Release

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    tags:
      - '*'

jobs:
  docker:
    name: Build the docker image
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/greptimeteam/greptimedb-operator:${{ github.ref_name }}
            greptime/greptimedb-operator:${{ github.ref_name }}

  release:
    name: Release artifacts
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Package charts
        run: |
          helm package ./charts/greptimedb-operator
          helm package ./charts/greptimedb

      - name: Rename packages
        run: |
          mv greptimedb-${{ github.ref_name }}.tgz greptimedb-${{ github.ref_name }}.charts.tgz
          mv greptimedb-operator-${{ github.ref_name }}.tgz greptimedb-operator-${{ github.ref_name }}.charts.tgz

      - name: Upload release asset
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            greptimedb-${{ github.ref_name }}.charts.tgz
            greptimedb-operator-${{ github.ref_name }}.charts.tgz
          token: ${{ secrets.GITHUB_TOKEN }}
