// Copyright 2022 Greptime Team
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	greptimedboperatorapisv1alpha1 "github.com/GreptimeTeam/greptimedb-operator/apis/v1alpha1"
	versioned "github.com/GreptimeTeam/greptimedb-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/GreptimeTeam/greptimedb-operator/pkg/client/informers/externalversions/internalinterfaces"
	apisv1alpha1 "github.com/GreptimeTeam/greptimedb-operator/pkg/client/listers/apis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GreptimeDBStandaloneInformer provides access to a shared informer and lister for
// GreptimeDBStandalones.
type GreptimeDBStandaloneInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apisv1alpha1.GreptimeDBStandaloneLister
}

type greptimeDBStandaloneInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGreptimeDBStandaloneInformer constructs a new informer for GreptimeDBStandalone type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGreptimeDBStandaloneInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGreptimeDBStandaloneInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGreptimeDBStandaloneInformer constructs a new informer for GreptimeDBStandalone type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGreptimeDBStandaloneInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApisV1alpha1().GreptimeDBStandalones(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApisV1alpha1().GreptimeDBStandalones(namespace).Watch(context.TODO(), options)
			},
		},
		&greptimedboperatorapisv1alpha1.GreptimeDBStandalone{},
		resyncPeriod,
		indexers,
	)
}

func (f *greptimeDBStandaloneInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGreptimeDBStandaloneInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *greptimeDBStandaloneInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&greptimedboperatorapisv1alpha1.GreptimeDBStandalone{}, f.defaultInformer)
}

func (f *greptimeDBStandaloneInformer) Lister() apisv1alpha1.GreptimeDBStandaloneLister {
	return apisv1alpha1.NewGreptimeDBStandaloneLister(f.Informer().GetIndexer())
}
